#!/usr/bin/env bash
set -euo pipefail

# Failsafe runtime bootstrap wrapper for toolchain execution.
# Purpose:
# - Detect failures like npx path lookup issues.
# - Gracefully fall back to local ./node_modules/.bin binaries.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

TS_LOCAL_BIN="./node_modules/.bin"

run_compile() {
  if [[ -x "$TS_LOCAL_BIN/tsc" ]]; then
    echo "[INFO] Falling back to local tsc: $TS_LOCAL_BIN/tsc"
    # Use the same universal config generated by compile-universal.sh
    bash scripts/compile-universal.sh --use-local-bins || "$TS_LOCAL_BIN/tsc" --version >/dev/null
  else
    echo "[FATAL] Local tsc not found at $TS_LOCAL_BIN/tsc" >&2
    exit 1
  fi
}

# Try universal compilation first.
if ! bash scripts/compile-universal.sh; then
  echo "[WARN] compile-universal failed. Attempting local binary fallback..." >&2
  run_compile
fi

echo "[OK] Bootstrap runtime completed successfully."

