#!/usr/bin/env bash
set -euo pipefail

# scripts/migrate-offline-records.sh
# ----------------------------------
# Offline record sync utility for local sandboxing and outage recovery.
# - Must use project-local relative paths.
# - Does not require production credentials.
# - Validates offline payload integrity before attempting re-sync.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

OFFLINE_DIR="${OFFLINE_DIR:-./.tmp/offline-records}"
STATE_LEDGER_DIR="${STATE_LEDGER_DIR:-./.tmp/state-ledger-mirror}"

MD_REPORT=".tmp/offline-migration-report.md"
mkdir -p .tmp

cat > "$MD_REPORT" <<'MD'
# Offline Records Migration Report

_Generated by scripts/migrate-offline-records.sh_
MD

append_md() {
  echo >> "$MD_REPORT"
  echo "$1" >> "$MD_REPORT"
}

require_dir() {
  local d="$1"
  if [[ ! -d "$d" ]]; then
    echo "[WARN] Directory not found: $d" >&2
    return 1
  fi
  return 0
}

verify_record_integrity() {
  local f="$1"

  # Accept JSON-only offline records.
  if [[ ! "$f" =~ \.json$ ]]; then
    return 1
  fi

  # Basic validity check (jq required).
  if command -v jq >/dev/null 2>&1; then
    jq -e . "$f" >/dev/null
    return 0
  fi

  # If jq missing, only ensure file is non-empty.
[[ -s "$f" ]]
}


migrate_sequential() {
  local files
  files=$(find "$OFFLINE_DIR" -maxdepth 1 -type f -name '*.json' | sort)

  if [[ -z "$files" ]]; then
    echo "[INFO] No offline records to migrate."
    append_md "✅ No offline records present in ${OFFLINE_DIR}."
    return 0
  fi

  echo "[INFO] Migrating offline records..."

  local migrated=0
  while IFS= read -r f; do
    echo "[INFO] Verifying: $f"

    if ! verify_record_integrity "$f"; then
      echo "[WARN] Skipping invalid record: $f" >&2
      continue
    fi

    # Host integration point:
    # If the repository contains a local re-sync command, it can be invoked here.
    # For now, we perform a safe simulation by copying into a ledger mirror directory.
    mkdir -p "$STATE_LEDGER_DIR"
    cp "$f" "$STATE_LEDGER_DIR/""

    migrated=$((migrated+1))
  done <<< "$files"

  append_md "✅ Migrated ${migrated} offline record(s) into mirror directory: ${STATE_LEDGER_DIR}."
  return 0
}

main() {
  require_dir "$OFFLINE_DIR" || {
    append_md "⚠️ Offline directory missing; nothing to migrate."
    echo "[OK] Report: $MD_REPORT"
    cat "$MD_REPORT"
    exit 0
  }

  migrate_sequential

  echo "[OK] Report written to $MD_REPORT"
  cat "$MD_REPORT"
}

main "$@"

