#!/usr/bin/env bash
set -euo pipefail

# scripts/verify-local-mesh.sh
# -----------------------------------------
# Lightweight local harness for verifying an end-to-end mesh:
# - container build validation
# - universal compilation
# - optional emulator connectivity
# - simple smoke checks
#
# Designed to run with relative paths and project-local binaries.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MD_REPORT=".tmp/verify-local-mesh-report.md"
mkdir -p .tmp

print_header() {
  cat > "$MD_REPORT" <<'MD'
# Local Mesh Verification Report

_Generated by scripts/verify-local-mesh.sh_
MD
}

append_md() {
  {
    echo
    echo "$1"
  } >> "$MD_REPORT"
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "[WARN] Missing command: $cmd" >&2
    return 1
  fi
  return 0
}

run_step() {
  local label="$1"
  local fn="$2"
  echo "[INFO] ${label}"

  if "$fn" >> "$MD_REPORT" 2>&1; then
    echo "✅ ${label}" >> "$MD_REPORT"
  else
    echo "❌ ${label}" >> "$MD_REPORT"
    exit 1
  fi
}

step_universal_compile() {
  echo "## Step: Universal compilation"
  echo
  # Prefer local compilation runner
  if [[ -x "./scripts/compile-universal.sh" ]]; then
    bash ./scripts/compile-universal.sh
  else
    echo "compile-universal.sh missing" >&2
    return 1
  fi
}

step_container_build() {
  echo "## Step: Dockerfile multi-stage build"
  echo
  if ! require_cmd docker; then
    echo "Docker not available; skipping container build." >&2
    return 0
  fi

  docker build -t univer-escrow-local-verify:latest .
  return 0
}

step_optional_emulator() {
  echo "## Step: Optional Firestore emulator connectivity"
  echo

  local host="${FIRESTORE_EMULATOR_HOST:-}"
  if [[ -z "$host" ]]; then
    echo "FIRESTORE_EMULATOR_HOST not set; skipping connectivity matrix." >&2
    return 0
  fi

  # Best effort curl check
  if require_cmd curl; then
    curl -fsS "http://${host}/" >/dev/null || return 1
  else
    echo "curl missing; cannot probe emulator." >&2
    return 0
  fi
}

main() {
  print_header

  echo
  echo "---"
  echo "## Step 1: Universal compilation"
  echo
  step_universal_compile

  echo
  echo "---"
  echo "## Step 2: Container build (best effort)"
  echo
  step_container_build || true

  echo
  echo "---"
  echo "## Step 3: Emulator connectivity (optional)"
  echo
  step_optional_emulator || true

  append_md "---\n✅ Local mesh verification completed."
  echo "[OK] Report written to $MD_REPORT"
  echo "---"
  cat "$MD_REPORT"
}

main "$@"

